//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 03:30:39 下午 CST 
//


package com.aotain.zongfen.bean;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pushId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="return_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiver">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="emailReceiver" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sendData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pushId",
    "returnAddress",
    "receiver",
    "subject",
    "sendData",
    "timeStamp"
})
@XmlRootElement(name = "emailPush")
public class EmailPush extends BasePush {

    protected long pushId;
    @XmlElement(name = "return_address", required = true)
    protected String returnAddress;
    @XmlElement(required = true)
    protected EmailPush.Receiver receiver;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String sendData;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the pushId property.
     * 
     */
    public long getPushId() {
        return pushId;
    }

    /**
     * Sets the value of the pushId property.
     * 
     */
    public void setPushId(long value) {
        this.pushId = value;
    }

    /**
     * Gets the value of the provinceShort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddress() {
        return returnAddress;
    }

    /**
     * Sets the value of the provinceShort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddress(String value) {
        this.returnAddress = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link EmailPush.Receiver }
     *     
     */
    public EmailPush.Receiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailPush.Receiver }
     *     
     */
    public void setReceiver(EmailPush.Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the sendData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendData() {
        return sendData;
    }

    /**
     * Sets the value of the sendData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendData(String value) {
        this.sendData = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    @Override
    public String toString() {
    	String receiverToString = ""; 
    	if (!this.receiver.getEmailReceiver().isEmpty()) { 
    		for (String receiver : this.receiver.getEmailReceiver()) { 
    			receiverToString += receiver; 
    		}
    	}
    	return "EmailPush [pushId=" + pushId + ",returnAddress=" + returnAddress + ",receiver=[" + receiverToString + "],subject" + subject + ",sendData=" + sendData + ",timeStamp=" + timeStamp + "]";
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="emailReceiver" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emailReceiver"
    })
    public static class Receiver {

        @XmlElement(required = true)
        protected List<String> emailReceiver;

        /**
         * Gets the value of the emailReceiver property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the emailReceiver property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmailReceiver().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEmailReceiver() {
            if (emailReceiver == null) {
                emailReceiver = new ArrayList<String>();
            }
            return this.emailReceiver;
        }

		public void setEmailReceiver(List<String> emailReceiver) {
			this.emailReceiver = emailReceiver;
		}

    }

}
