//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 03:30:39 下午 CST 
//


package com.aotain.zongfen.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aotain.push.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aotain.push.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IsmsPushAck }
     * 
     */
    public IsmsPushAck createIsmsPushAck() {
        return new IsmsPushAck();
    }

    /**
     * Create an instance of {@link EmailPush.Receiver }
     * 
     */
    public EmailPush.Receiver createEmailPushReceiver() {
        return new EmailPush.Receiver();
    }

    /**
     * Create an instance of {@link PhonePush.Receiver }
     * 
     */
    public PhonePush.Receiver createPhonePushReceiver() {
        return new PhonePush.Receiver();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link WeChatPush }
     * 
     */
    public WeChatPush createWeChatPush() {
        return new WeChatPush();
    }

    /**
     * Create an instance of {@link EmailPush }
     * 
     */
    public EmailPush createEmailPush() {
        return new EmailPush();
    }

    /**
     * Create an instance of {@link WeChatPush.SendData }
     * 
     */
    public WeChatPush.SendData createWeChatPushSendData() {
        return new WeChatPush.SendData();
    }

    /**
     * Create an instance of {@link WeChatPush.Receiver }
     * 
     */
    public WeChatPush.Receiver createWeChatPushReceiver() {
        return new WeChatPush.Receiver();
    }

    /**
     * Create an instance of {@link IsmsPushAck.PushAck }
     * 
     */
    public IsmsPushAck.PushAck createIsmsPushAckPushAck() {
        return new IsmsPushAck.PushAck();
    }

    /**
     * Create an instance of {@link PhonePush }
     * 
     */
    public PhonePush createPhonePush() {
        return new PhonePush();
    }

}
