//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 03:30:39 下午 CST 
//


package com.aotain.zongfen.bean;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ackId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pushAck" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pushId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="msgInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ackId",
    "pushAck",
    "timeStamp"
})
@XmlRootElement(name = "ismsPushAck")
public class IsmsPushAck {

    @XmlElement(required = true)
    protected String ackId;
    @XmlElement(required = true)
    protected List<IsmsPushAck.PushAck> pushAck;
    @XmlElement(required = true)
    protected String timeStamp;

    /**
     * Gets the value of the ackId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAckId() {
        return ackId;
    }

    /**
     * Sets the value of the ackId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAckId(String value) {
        this.ackId = value;
    }

    /**
     * Gets the value of the pushAck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pushAck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPushAck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IsmsPushAck.PushAck }
     * 
     * 
     */
    public List<IsmsPushAck.PushAck> getPushAck() {
        if (pushAck == null) {
            pushAck = new ArrayList<IsmsPushAck.PushAck>();
        }
        return this.pushAck;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pushId" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="msgInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pushId",
        "type",
        "resultCode",
        "msgInfo"
    })
    public static class PushAck {

        protected long pushId;
        @XmlElement(required = true)
        protected BigInteger type;
        @XmlElement(required = true)
        protected BigInteger resultCode;
        protected String msgInfo;

        /**
         * Gets the value of the pushId property.
         * 
         */
        public long getPushId() {
            return pushId;
        }

        /**
         * Sets the value of the pushId property.
         * 
         */
        public void setPushId(long value) {
            this.pushId = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setType(BigInteger value) {
            this.type = value;
        }

        /**
         * Gets the value of the resultCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getResultCode() {
            return resultCode;
        }

        /**
         * Sets the value of the resultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setResultCode(BigInteger value) {
            this.resultCode = value;
        }

        /**
         * Gets the value of the msgInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMsgInfo() {
            return msgInfo;
        }

        /**
         * Sets the value of the msgInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMsgInfo(String value) {
            this.msgInfo = value;
        }

    }

}
