//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 03:30:39 下午 CST 
//


package com.aotain.zongfen.bean;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pushId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="province_short" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gatewayType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="smgpVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiver">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="phoneReceiver" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sendData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pushId",
    "provinceShort",
    "gatewayType",
    "smgpVersion",
    "receiver",
    "sendData",
    "timeStamp"
})
@XmlRootElement(name = "phonePush")
public class PhonePush extends BasePush {

    protected long pushId;
    @XmlElement(required = true)
    protected BigInteger gatewayType;
    @XmlElement(required = true)
    protected String smgpVersion;
    @XmlElement(required = true)
    protected PhonePush.Receiver receiver;
    @XmlElement(required = true)
    protected String sendData;
    @XmlElement(required = true)
    protected String timeStamp;
    @XmlElement(name = "return_Address", required = true)
    protected String returnAddress;

    /**
     * Gets the value of the pushId property.
     * 
     */
    public long getPushId() {
        return pushId;
    }

    /**
     * Sets the value of the pushId property.
     * 
     */
    public void setPushId(long value) {
        this.pushId = value;
    }

    /**
     * Gets the value of the gatewayType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGatewayType() {
        return gatewayType;
    }

    /**
     * Sets the value of the gatewayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGatewayType(BigInteger value) {
        this.gatewayType = value;
    }

    /**
     * Gets the value of the smgpVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmgpVersion() {
        return smgpVersion;
    }

    /**
     * Sets the value of the smgpVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmgpVersion(String value) {
        this.smgpVersion = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link PhonePush.Receiver }
     *     
     */
    public PhonePush.Receiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhonePush.Receiver }
     *     
     */
    public void setReceiver(PhonePush.Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the sendData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendData() {
        return sendData;
    }

    /**
     * Sets the value of the sendData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendData(String value) {
        this.sendData = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    public String getReturnAddress() {
		return returnAddress;
	}

	public void setReturnAddress(String returnAddress) {
		this.returnAddress = returnAddress;
	}


	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="phoneReceiver" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phoneReceiver"
    })
    public static class Receiver {

        @XmlElement(required = true)
        protected List<String> phoneReceiver;

        /**
         * Gets the value of the phoneReceiver property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the phoneReceiver property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoneReceiver().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPhoneReceiver() {
            if (phoneReceiver == null) {
                phoneReceiver = new ArrayList<String>();
            }
            return this.phoneReceiver;
        }

		public void setPhoneReceiver(List<String> phoneReceiver) {
			this.phoneReceiver = phoneReceiver;
		}

    }

}
